[project]
name = "Eccelerators.Cli"
version = "1.0.0"
path = "src"
outdir = "out"

[dependencies]
"Livt.IO" = { path = "../livt-io" }

[tests]
path = "tests"
components = [
    "CliOutputTest",
    "CompactCliTest",
    "CliLineEditorTest",
    "CliParserTest",
    "CliTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
