[project]
name = "Eccelerators.Cli"
version = "1.2.0-dev"
path = "src"
outdir = "out"

[dependencies]
"Livt.IO" = "1.2.0-dev"

[tests]
path = "tests"
components = [
    "CliOutputTest",
    "CompactCliTest",
    "CompactCliEchoTest",
    "CliUartIntegrationTest",
    "CliLineEditorTest",
    "CliParserTest",
    "CliTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
